config/routes.rb
Rails.application.routes.draw do
  get 'store/index'

  resources :books
  resource :line_items

  root :to => 'store#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :line_items

  before_validation :whitespace_removing

  validates :title, :description, :image_url, presence: true

  validates :title, uniqueness:{case_sensitive: false}, length:{maximum: 50}

  validates :price, presence: true, numericality: {greater_than_or_equal_to: 0.01}

  validates :discount_price, allow_blank: true, numericality: {greater_than_or_equal_to: 0.00}
  validate :discount_price_cannot_be_greater_than_original_price

  validates :image_url, format: {
      with: %r{\.(gif|jpg|png)\Z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'
  }

  def discount_price_cannot_be_greater_than_original_price
    if self.discount_price? && self.price?
      if self.discount_price > self.price
      errors.add(:discount_price, "Can't Be Greater Then Price")
      end
    end
  end

  def whitespace_removing
    self.title = title.gsub(/\s+/, ' ').strip
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #applicable to rails 2.2


  #private
  #def current_cart
   # Cart.find(session[:cart_id])
  #rescue ActiveRecord::RecordNotFound
  #  cart = Cart.create
   # session[:cart_id] = cart.id
   # cart
  #end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @free = 'Book is Free'
  end
  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :image_url, :price, :discount_price)
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  private
  def current_cart
   Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
   session[:cart_id] = cart.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description,:rows => 6, :cols => 50 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :discount_price %><br>
    <%= f.text_field :discount_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book, class: 'buttonCss'%> |
<%= link_to 'Back', books_path, class: 'buttonCss'%>

app/views/books/index.html.erb
<h1>BOOKSHELF CATALOG</h1>
<hr />


<table>
  <tbody>
    <% @books.each do |book| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= link_to image_tag(book.image_url, class: 'list_image'), book  %></td>
        <td>
        <div class="title"><%= link_to book.title, book  %></div>
        <div class="description">Description: <%= book.description %></div>
        <% if book.price == book.discount_price %>
        <div class="free">Price: <%= @free %></div>
        <% else %>
        <div class="price">Price: <%=number_to_currency  (book.price) %></div>
        <% if book.discount_price != nil %>
        <div class="discount_price">Discount_price: <%=number_to_currency (book.discount_price) %></div>
        <% end %>
        <% end %>
        <div class="links"><%= link_to 'Show', book, class: 'buttonCss' %> | <%= link_to 'Edit', edit_book_path(book),class:'buttonCss' %> | <%= link_to 'Delete', book,class: 'buttonCss', method: :delete, data: { confirm: 'Are you sure?' } %></div>
        </td>
      </tr>
      <tr><td colspan="2">
        <hr />
      </td></tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path ,class: 'buttonCss'%>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path,class: 'buttonCss' %>

app/views/books/show.html.erb
<h1>Show</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @book.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Discount price:</strong>
  <%= @book.discount_price %>
</p>

<%= link_to 'Edit', edit_book_path(@book),class:'buttonCss' %> |
<%= link_to 'Back', books_path,class: 'buttonCss' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books Online Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>